#!/usr/bin/env bash
# the story of passwd file
exec 3< /etc/passwd

IFS=:

while read -r username _ uid gid info home shell; do

    group=$(getent group "$gid" | cut -d: -f1)

    user_info=$(finger "$username" 2>/dev/null | awk -F: 'NR==2 {print $3}')

    password=$(getent shadow "$username" | cut -d: -f2)

    echo "The user $username is part of the $group gang, lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_info"
done <&3
exec 3<&-
