#!/usr/bin/env bash
# task is about installing nginx onto our server
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a HTML file with "Hello World!" content
echo "<!DOCTYPE html>
<html>
<head>
<title>Hello World!</title>
</head>
<body>
<h1>Hello World!</h1>
</body>
</html>" > /var/www/html/index.html

# Restart nginx without using systemctl
service nginx stop
service nginx start
