#!/usr/bin/env bash
# Update package index and redirect
sed -i 's#location / {#location / {\n\tlocation /redirect_me {\n\t\treturn 301 https://www.example.com;\n\t}#' /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx restart
