#!/usr/bin/env bash
# liberating the port 80 for curlin
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop
service nginx start
