#!/usr/bin/env bash
# advanced 100
sig_t()  {
	echo "I hate the kill command"
}
sigi() {
	echo "Y U no love me?!"
}
Q_sig() {
	rm "/var/run/myscript.pid"
	kill "$$"
}
trap 'sig_t;Q-sig' SIGTERM
trap 'sigi;Q_sig' SIGINT
trap 'Q_sig' SIGQUIT
fil="/var/run/myscript.pid"
touch "$fil"
cat "$$" > "$fil"
while true; do
	echo "To infinity and beyond"
done
