#!/usr/bin/env bash
# task for managing codes in other file
case "$1" in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        exit 1
esac
