#!/usr/bin/env bash
# task for managing codes in other file
case "$1" in
    start)
        ./manage_my_process &
        touch "/var/run/my_process.pid"
	echo $! > /var/run/my_process.pid
        ;;
    stop)
        p_to_k=$(</var/run/my_process.pid)
        pkill -15 "$p_to_k"
	rm /var/run/my_process.pid
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        exit 1
esac
