#!/usr/bin/env bash
# this is the use of case in a loop
iter="1"
while [ $iter -le 20 ]
do
	case $iter in
	4)
		echo "$iter"
		echo "bad luck from China"
	;;
	9)
		echo "$iter"
		echo "bad luck from Japan"
	;;
	17)
		echo "$iter"
		echo "bad luck from Italy"
	;;
	*)
		echo "$iter"
	esac
	(( iter++ ))
done
		
