#!/usr/bin/env bash
# Loop through each file in the current directory
for file in *; do
	if [[ ! "$file" == .* && -f "$file" ]]; then
                name=$(echo "$file" | cut -d'-' -f 2-)
               echo "$name"
	fi
done
