#!/usr/bin/env bash
# remove 2 chars of each file name in current dir
for flei in *; do
	if [[ ! "$flei" == .* && -f "$flei" ]]; then
                name=$(echo "$flei" | cut -d'-' -f 2-)
               echo "$name"
	fi
done
