#!/usr/bin/env bash
# task 1 abiut reconfiguring a server to avoid using root usr
sudo apt-get install -y nginx
sudo sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo service nginx restart
