#!/usr/bin/env bash
# task 1 abiut reconfiguring a server to avoid using root usr
sudo apt-get update
sudo apt-get install -y nginx

sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/www/html
service nginx restart
