#!/usr/bin/env bash
# task 1 abiut reconfiguring a server to avoid using root usr

if ! id nginx &> /dev/null; then
  adduser --system --group --no-shell nginx
fi
# Change ownership of Nginx directories
chown -R nginx:nginx /etc/nginx /var/lib/nginx
# Update Nginx configuration
sed -i 's/user root;/user nginx;/' /etc/nginx/nginx.conf
# Update worker_processes dir
chmod -R 755 /var/lib/nginx/sockets
